### PR TITLE
Fall 2023 - Autograder comptability

### PR DESCRIPTION
**Pull request by AndrewQuijano**
I got the following:
1- Fixed typos in README
2- removed import_dbs.sh, so the instruction to import dbs is now OS agnostic
3- Update settings.py to be able to use Django Gradescope Runner.

I do need the following opinons from the staff about changes:

1- Should we just specifically state about using Environment variable and the variable name?

2- I think to allow easy autograding, we might need to specifically state which libraries they can use? This will become a bit more clear once the last part of the autograder is complete

### CODE REVIEW

**Comment by AndrewQuijano** [comment]
Oh I also need to update OS injection instructions. I'll do that shortly

**Comment by waheed042** [comment]
hello sir this men is scammer
he is asking me to do his work , i did his work now he is  not paying me

**Comment by waheed042** [comment]
he gave me his login and password

**Review by kcg295 — APPROVED** [review]

**Comment by kcg295** [comment]
> hello sir this men is scammer he is asking me to do his work , i did his work now he is not paying me

We will look into this, and what can be done. Thank you for the notification.

**Comment by waheed042** [comment]
please say to account holder to pay my fee as well he is scamming with teacher as well as me

**Comment by waheed042** [comment]
brother did you do something for scammer? he is not paying me

**Pull request merged**
